version: '3.1'

services:
  app:
    build: ./
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - "db"
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: animals
